/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    colors: Color;
    encrypted: Encrypted;
    icons: Icon;
    measurements: Measurement;
    'phone-numbers': PhoneNumber;
    'write-only-stories': WriteOnlyStory;
    tenants: Tenant;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    colors: ColorsSelect<false> | ColorsSelect<true>;
    encrypted: EncryptedSelect<false> | EncryptedSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    measurements: MeasurementsSelect<false> | MeasurementsSelect<true>;
    'phone-numbers': PhoneNumbersSelect<false> | PhoneNumbersSelect<true>;
    'write-only-stories': WriteOnlyStoriesSelect<false> | WriteOnlyStoriesSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'smtp-settings': SmtpSetting;
  };
  globalsSelect: {
    'smtp-settings': SmtpSettingsSelect<false> | SmtpSettingsSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: string;
  title: string;
  nativeText?: string | null;
  hexDefault?: string | null;
  rgbFormat?: string | null;
  hslFormat?: string | null;
  oklchFormat?: string | null;
  noAlpha?: string | null;
  noEyedropper?: string | null;
  notClearable?: string | null;
  withPresets?: string | null;
  pluginPresets?: string | null;
  requiredColor: string;
  readOnlyColor?: string | null;
  localizedColor?: string | null;
  linkedStatic?: string | null;
  linkedStaticResolved?: string | null;
  linkedNoAlpha?: string | null;
  linkedNoAlphaResolved?: string | null;
  linkedTenant?: string | null;
  linkedTenantResolved?: string | null;
  linkedSchemes?: string | null;
  linkedSchemesResolved?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemePresetsFlat?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encrypted".
 */
export interface Encrypted {
  id: string;
  label: string;
  fullName: string;
  apiKey?: string;
  notes?: string;
  webhookSecret?: string;
  webhookSecret_set?: boolean | null;
  contactEmail?: string;
  contactEmail_bidx?: string | null;
  salary?: number;
  isVip?: boolean;
  birthday?: string;
  tier?: 'free' | 'pro' | 'enterprise';
  channels?: ('email' | 'sms' | 'push')[];
  referral?: 'friend' | 'ad' | 'search';
  apiSnippet?: string;
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * @minItems 2
   * @maxItems 2
   */
  lastKnownLocation?: [number, number];
  /**
   * richText field. Masked, the full editor mounts on reveal (blocks included).
   */
  privateNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  privateNotes_encrypted?: string | null;
  /**
   * richText field. protection 'none': the full editor renders directly, encrypted at rest.
   */
  draftBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  draftBody_encrypted?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: string;
  title: string;
  /**
   * Pick a tenant to scope the Tenant-scoped field below to its enabled libraries.
   */
  tenant?: (string | null) | Tenant;
  /**
   * All registered libraries; the drawer shows a library switcher.
   */
  iconMulti?: string | null;
  /**
   * Only Lucide is offered, so the drawer hides the switcher.
   */
  iconSingle?: string | null;
  /**
   * Type or paste a raw library:name (e.g. lucide:star), or pick from the drawer.
   */
  iconWithText?: string | null;
  /**
   * Required: a valid library:name must be set before the document can save.
   */
  iconRequired: string;
  /**
   * resolveAvailable reads the selected tenant's enabledLibraries. Acme enables Lucide and Radix, so its drawer shows a switcher for those two; Globex enables only Tabler, so the switcher is hidden. An icon stored from a library the tenant no longer enables still renders, but is flagged as unavailable with a banner in the drawer.
   */
  iconTenantRestricted?: string | null;
  /**
   * The Social library is forced-available in every tenant via alwaysAvailable; other libraries are gated by the tenant's enabledLibraries. Both Acme and Globex show Social in the switcher even though neither enables it.
   */
  iconWithForced?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  enabledLibraries?: string[] | null;
  primary?: string | null;
  accent?: string | null;
  brandColors?:
    | {
        key: string;
        label?: string | null;
        value: string;
        valueDark?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements".
 */
export interface Measurement {
  id: string;
  title: string;
  nativeNumber?: number | null;
  weight?: number | null;
  /**
   * Compound ft+in entry when toggled imperial
   */
  height?: number | null;
  distance?: number | null;
  load?: number | null;
  wingspan?: number | null;
  volume?: number | null;
  temperature?: number | null;
  speed?: number | null;
  poundsFirst?: number | null;
  kgOnly?: number | null;
  boundedWeight: number;
  readOnlyWeight?: number | null;
  localizedDistance?: number | null;
  /**
   * Free-form: inches only, stored in millimetres, its own preference bucket
   */
  cutout?: number | null;
  /**
   * Free-form with a custom unit (nmi, 1 nmi = 1852 m). No Intl unit for nmi, so it formats as a plain decimal plus shortLabel
   */
  sailing?: number | null;
  /**
   * Exact mode: free entry (no quantize), faithful drafts, cells read back at full storage precision
   */
  labSample?: number | null;
  /**
   * Readable mode with storage rounded to whole grams: the granularity contract runs on every write, regardless of what produced the number
   */
  shippingWeight?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-numbers".
 */
export interface PhoneNumber {
  id: string;
  title: string;
  nativeText?: string | null;
  phone?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * Native text field outside a row: the phone rows below must share its height, border, radius and margin-bottom
   */
  nativeStacked?: string | null;
  /**
   * storage e164: one indexed text column holding the raw E.164 string. Also carries admin.placeholder, className, style, and custom Error/beforeInput/afterInput components
   */
  e164Phone?: string | null;
  /**
   * validation possible: length alone decides
   */
  possibleValidation?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * validation valid: the number must match a real range
   */
  strictValidation?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * validation mobile: a landline is rejected, which needs metadata max or mobile
   */
  mobileOnly?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * flags svg: artwork served by the plugin endpoint
   */
  svgFlags?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * flags emoji: regional indicator pairs, no artwork
   */
  emojiFlags?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * flags none: the trigger shows the ISO code instead
   */
  noFlags?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * countries allowlist of six, defaulting to CH, seeded with a JP number the allowlist does not offer: an allowlist scopes the picker, not what a pasted number may commit
   */
  allowlisted?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * The seed is sibling-scoped, so a row must read its own value
   */
  contacts?:
    | {
        role?: string | null;
        phone?: {
          number?: string | null;
          country?: string | null;
          national?: string | null;
          international?: string | null;
          callingCode?: string | null;
          uri?: string | null;
          type?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * preferredCountries overriding the plugin-wide DE/AT/CH, so the picker heads with JP/KR/SG
   */
  preferredFirst?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * defaultCountry US: opening the picker has to scroll far down the list to reach it
   */
  usDefault?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * cellFormat national: check the list view column
   */
  nationalCell?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * cellFormat e164: check the list view column
   */
  e164Cell?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * required: no clear control, and empty fails to save
   */
  requiredPhone: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  nativeReadOnly?: string | null;
  /**
   * admin.readOnly, which reaches a custom Field component only via clientField
   */
  readOnlyPhone?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * localized: one number per admin locale
   */
  localizedPhone?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * isClearable false: emptying the input and committing reverts to the last valid value
   */
  notClearable?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * A localized static label, not the humanized name
   */
  labelled?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  customComponents?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  /**
   * Toggles the conditional phone field below
   */
  showConditional?: boolean | null;
  /**
   * admin.condition, driven by the checkbox above
   */
  conditionalPhone?: {
    number?: string | null;
    country?: string | null;
    national?: string | null;
    international?: string | null;
    callingCode?: string | null;
    uri?: string | null;
    type?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * One field per write-only user story. The input is always editable: a stored value is only a placeholder (hint or dots), typing stages a replacement, emptying the input keeps the stored value, and every action lives inside the input row.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "write-only-stories".
 */
export interface WriteOnlyStory {
  id: string;
  label: string;
  smtpPassword?: string;
  smtpPassword_set?: boolean | null;
  stripeKey?: string;
  stripeKey_set?: boolean | null;
  stripeKey_hint?: string | null;
  webhookSecret?: string;
  webhookSecret_set?: boolean | null;
  tenantApiKey?: string;
  tenantApiKey_set?: boolean | null;
  tenantApiKey_hint?: string | null;
  dbPassword?: string;
  rotationSecret: string;
  rotationSecret_set?: boolean | null;
  rotationSecret_hint?: string | null;
  stripeLiveKey?: string;
  stripeLiveKey_set?: boolean | null;
  stripeLiveKey_hint?: string | null;
  /**
   * Native neighbour at the same width, for comparison: both inputs must be the same height and the same width, and the encrypted one must not push this one out of the row.
   */
  rowNeighbour?: string | null;
  longLivedToken?: string;
  longLivedToken_set?: boolean | null;
  longLivedToken_hint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'colors';
        value: string | Color;
      } | null)
    | ({
        relationTo: 'encrypted';
        value: string | Encrypted;
      } | null)
    | ({
        relationTo: 'icons';
        value: string | Icon;
      } | null)
    | ({
        relationTo: 'measurements';
        value: string | Measurement;
      } | null)
    | ({
        relationTo: 'phone-numbers';
        value: string | PhoneNumber;
      } | null)
    | ({
        relationTo: 'write-only-stories';
        value: string | WriteOnlyStory;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  title?: T;
  nativeText?: T;
  hexDefault?: T;
  rgbFormat?: T;
  hslFormat?: T;
  oklchFormat?: T;
  noAlpha?: T;
  noEyedropper?: T;
  notClearable?: T;
  withPresets?: T;
  pluginPresets?: T;
  requiredColor?: T;
  readOnlyColor?: T;
  localizedColor?: T;
  linkedStatic?: T;
  linkedStaticResolved?: T;
  linkedNoAlpha?: T;
  linkedNoAlphaResolved?: T;
  linkedTenant?: T;
  linkedTenantResolved?: T;
  linkedSchemes?: T;
  linkedSchemesResolved?: T;
  schemePresetsFlat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "encrypted_select".
 */
export interface EncryptedSelect<T extends boolean = true> {
  label?: T;
  fullName?: T;
  apiKey?: T;
  notes?: T;
  webhookSecret?: T;
  webhookSecret_set?: T;
  contactEmail?: T;
  contactEmail_bidx?: T;
  salary?: T;
  isVip?: T;
  birthday?: T;
  tier?: T;
  channels?: T;
  referral?: T;
  apiSnippet?: T;
  metadata?: T;
  lastKnownLocation?: T;
  privateNotes?: T;
  privateNotes_encrypted?: T;
  draftBody?: T;
  draftBody_encrypted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  title?: T;
  tenant?: T;
  iconMulti?: T;
  iconSingle?: T;
  iconWithText?: T;
  iconRequired?: T;
  iconTenantRestricted?: T;
  iconWithForced?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "measurements_select".
 */
export interface MeasurementsSelect<T extends boolean = true> {
  title?: T;
  nativeNumber?: T;
  weight?: T;
  height?: T;
  distance?: T;
  load?: T;
  wingspan?: T;
  volume?: T;
  temperature?: T;
  speed?: T;
  poundsFirst?: T;
  kgOnly?: T;
  boundedWeight?: T;
  readOnlyWeight?: T;
  localizedDistance?: T;
  cutout?: T;
  sailing?: T;
  labSample?: T;
  shippingWeight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-numbers_select".
 */
export interface PhoneNumbersSelect<T extends boolean = true> {
  title?: T;
  nativeText?: T;
  phone?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  nativeStacked?: T;
  e164Phone?: T;
  possibleValidation?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  strictValidation?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  mobileOnly?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  svgFlags?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  emojiFlags?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  noFlags?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  allowlisted?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  contacts?:
    | T
    | {
        role?: T;
        phone?:
          | T
          | {
              number?: T;
              country?: T;
              national?: T;
              international?: T;
              callingCode?: T;
              uri?: T;
              type?: T;
            };
        id?: T;
      };
  preferredFirst?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  usDefault?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  nationalCell?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  e164Cell?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  requiredPhone?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  nativeReadOnly?: T;
  readOnlyPhone?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  localizedPhone?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  notClearable?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  labelled?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  customComponents?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  showConditional?: T;
  conditionalPhone?:
    | T
    | {
        number?: T;
        country?: T;
        national?: T;
        international?: T;
        callingCode?: T;
        uri?: T;
        type?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "write-only-stories_select".
 */
export interface WriteOnlyStoriesSelect<T extends boolean = true> {
  label?: T;
  smtpPassword?: T;
  smtpPassword_set?: T;
  stripeKey?: T;
  stripeKey_set?: T;
  stripeKey_hint?: T;
  webhookSecret?: T;
  webhookSecret_set?: T;
  tenantApiKey?: T;
  tenantApiKey_set?: T;
  tenantApiKey_hint?: T;
  dbPassword?: T;
  rotationSecret?: T;
  rotationSecret_set?: T;
  rotationSecret_hint?: T;
  stripeLiveKey?: T;
  stripeLiveKey_set?: T;
  stripeLiveKey_hint?: T;
  rowNeighbour?: T;
  longLivedToken?: T;
  longLivedToken_set?: T;
  longLivedToken_hint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  enabledLibraries?: T;
  primary?: T;
  accent?: T;
  brandColors?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        valueDark?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smtp-settings".
 */
export interface SmtpSetting {
  id: string;
  host?: string | null;
  user?: string | null;
  password?: string;
  password_set?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smtp-settings_select".
 */
export interface SmtpSettingsSelect<T extends boolean = true> {
  host?: T;
  user?: T;
  password?: T;
  password_set?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}