import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import type { IconManifest, IconNodeMap } from '../../../types'

const here = dirname(fileURLToPath(import.meta.url))

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/
const SVG_NODE_TAGS = new Set([
	'circle',
	'ellipse',
	'g',
	'line',
	'path',
	'polygon',
	'polyline',
	'rect',
])

const assertNodesCoverManifest = (manifest: IconManifest, nodes: IconNodeMap) => {
	const names = Object.keys(nodes)
	// One glyph per manifest icon, keyed identically, so the drawer always finds a glyph.
	expect(names.length).toBe(manifest.icons.length)
	for (const icon of manifest.icons) {
		const glyph = nodes[icon.name]
		expect(glyph).toBeDefined()
		if (!glyph) continue
		expect(glyph.length).toBeGreaterThan(0)
		for (const [tag, attrs] of glyph) {
			expect(SVG_NODE_TAGS.has(tag)).toBe(true)
			expect(typeof attrs).toBe('object')
		}
	}
}

const assertManifestShape = (manifest: IconManifest, minIcons: number) => {
	expect(manifest.icons.length).toBeGreaterThan(minIcons)
	const names = new Set<string>()
	const categorySet = new Set(manifest.categories)
	for (const icon of manifest.icons) {
		expect(icon.name).toMatch(KEBAB)
		expect(names.has(icon.name)).toBe(false)
		names.add(icon.name)
		expect(Array.isArray(icon.tags)).toBe(true)
		expect(icon.categories).toEqual([...icon.categories].sort())
		for (const category of icon.categories) expect(categorySet.has(category)).toBe(true)
	}
	expect(manifest.categories).toEqual([...manifest.categories].sort())
}

describe('committed adapter manifests', () => {
	it('lucide manifest is well formed', async () => {
		const { manifest } = await import('./lucide/generated/manifest')
		assertManifestShape(manifest, 1500)
		expect(manifest.icons.some((icon) => icon.name === 'house')).toBe(true)
		// Categories are fetched at generation time; an empty set means a regen
		// silently dropped them (see loadLucideSource).
		expect(manifest.categories.length).toBeGreaterThan(0)
	})

	it('lucide node-data covers the manifest for inline drawer rendering', async () => {
		const { manifest } = await import('./lucide/generated/manifest')
		const { nodes } = await import('./lucide/generated/nodes')
		assertNodesCoverManifest(manifest, nodes)
	})

	it('radix manifest is well formed and has an imports map', async () => {
		const { manifest } = await import('./radix/generated/manifest')
		assertManifestShape(manifest, 300)
		const { iconImports } = await import('./radix/generated/imports')
		expect(Object.keys(iconImports).length).toBe(manifest.icons.length)
	})

	it('tabler manifest is well formed and has an imports map', async () => {
		const { manifest } = await import('./tabler/generated/manifest')
		assertManifestShape(manifest, 4000)
		expect(manifest.categories.length).toBeGreaterThan(0)
		const { iconImports } = await import('./tabler/generated/imports')
		expect(Object.keys(iconImports).length).toBe(manifest.icons.length)
		expect(iconImports.heart).toBeDefined()
	})

	it('tabler node-data covers the manifest for inline drawer rendering', async () => {
		const { manifest } = await import('./tabler/generated/manifest')
		const { nodes } = await import('./tabler/generated/nodes')
		assertNodesCoverManifest(manifest, nodes)
	})

	// Radix ships React components rather than raw SVG, so its node-data is generated by
	// rendering each one at generation time. That is what moved it off the per-icon path.
	it('radix ships node-data so the drawer renders it in bulk', () => {
		expect(existsSync(join(here, 'radix/generated/nodes.ts'))).toBe(true)
	})
})
