/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'form-uploads': FormUpload;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'form-uploads': FormUploadsSelect<false> | FormUploadsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'form-builder-actions': TaskFormBuilderActions;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads".
 */
export interface FormUpload {
  id: string;
  owner?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            validations?:
              | (
                  | {
                      min: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'minLength';
                    }
                  | {
                      max: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'maxLength';
                    }
                  | {
                      pattern: string;
                      flags?: string | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'pattern';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'email';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'url';
                    }
                  | {
                      values?:
                        | {
                            value: string;
                            id?: string | null;
                          }[]
                        | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'oneOf';
                    }
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            validations?:
              | (
                  | {
                      min: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'minLength';
                    }
                  | {
                      max: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'maxLength';
                    }
                  | {
                      pattern: string;
                      flags?: string | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'pattern';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'email';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'url';
                    }
                  | {
                      values?:
                        | {
                            value: string;
                            id?: string | null;
                          }[]
                        | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'oneOf';
                    }
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            validations?:
              | (
                  | {
                      min: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'minLength';
                    }
                  | {
                      max: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'maxLength';
                    }
                  | {
                      pattern: string;
                      flags?: string | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'pattern';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'email';
                    }
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            validations?:
              | (
                  | {
                      min: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'min';
                    }
                  | {
                      max: number;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'max';
                    }
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            validations?:
              | (
                  | {
                      values?:
                        | {
                            value: string;
                            id?: string | null;
                          }[]
                        | null;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'oneOf';
                    }
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            validations?:
              | (
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            expression?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            calcDisplay?: boolean | null;
            validations?:
              | (
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'calculation';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            statement?: string | null;
            source?: ('static' | 'pageReference') | null;
            sourceConfig?: {
              label?: string | null;
              url?: string | null;
              version?: string | null;
              relationTo?: string | null;
              docId?: string | null;
              urlField?: string | null;
              captureVersion?: boolean | null;
            };
            optional?: boolean | null;
            validations?:
              | (
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'consent';
          }
        | {
            name: string;
            label?: string | null;
            required?: boolean | null;
            width?: ('full' | 'half' | 'third' | 'twoThirds') | null;
            placeholder?: string | null;
            description?: string | null;
            visibleWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            validateWhen?:
              | {
                  [k: string]: unknown;
                }
              | unknown[]
              | string
              | number
              | boolean
              | null;
            hidden?: boolean | null;
            relationTo?: string | null;
            mimeTypes?: string[] | null;
            maxSize?: number | null;
            validations?:
              | (
                  | {
                      field: string;
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'matchesField';
                    }
                  | {
                      message?: string | null;
                      severity?: ('error' | 'warning') | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'notAlreadySubmitted';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'file';
          }
      )[]
    | null;
  flow?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  actions?:
    | (
        | {
            to?: string | null;
            subject?: string | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'emailTeam';
          }
        | {
            toField?: string | null;
            subject?: string | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'confirmation';
          }
        | {
            url?: string | null;
            secret?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signedWebhook';
          }
      )[]
    | null;
  defaultPresentation?: ('page' | 'inline' | 'modal' | 'drawer') | null;
  showResults?: boolean | null;
  /**
   * Field whose aggregate results are public when "Show results publicly" is on. Use a choice field, never a free-text or PII field.
   */
  resultsField?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  status?: ('complete' | 'partial') | null;
  locale?: string | null;
  values?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  descriptors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consent?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'form-builder-actions';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'form-builder-actions') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'form-uploads';
        value: string | FormUpload;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads_select".
 */
export interface FormUploadsSelect<T extends boolean = true> {
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        text?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              validations?:
                | T
                | {
                    minLength?:
                      | T
                      | {
                          min?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    maxLength?:
                      | T
                      | {
                          max?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    pattern?:
                      | T
                      | {
                          pattern?: T;
                          flags?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    email?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    url?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    oneOf?:
                      | T
                      | {
                          values?:
                            | T
                            | {
                                value?: T;
                                id?: T;
                              };
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              validations?:
                | T
                | {
                    minLength?:
                      | T
                      | {
                          min?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    maxLength?:
                      | T
                      | {
                          max?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    pattern?:
                      | T
                      | {
                          pattern?: T;
                          flags?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    email?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    url?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    oneOf?:
                      | T
                      | {
                          values?:
                            | T
                            | {
                                value?: T;
                                id?: T;
                              };
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              validations?:
                | T
                | {
                    minLength?:
                      | T
                      | {
                          min?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    maxLength?:
                      | T
                      | {
                          max?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    pattern?:
                      | T
                      | {
                          pattern?: T;
                          flags?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    email?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              validations?:
                | T
                | {
                    min?:
                      | T
                      | {
                          min?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    max?:
                      | T
                      | {
                          max?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              validations?:
                | T
                | {
                    oneOf?:
                      | T
                      | {
                          values?:
                            | T
                            | {
                                value?: T;
                                id?: T;
                              };
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              validations?:
                | T
                | {
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        calculation?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              expression?: T;
              calcDisplay?: T;
              validations?:
                | T
                | {
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        consent?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              statement?: T;
              source?: T;
              sourceConfig?:
                | T
                | {
                    label?: T;
                    url?: T;
                    version?: T;
                    relationTo?: T;
                    docId?: T;
                    urlField?: T;
                    captureVersion?: T;
                  };
              optional?: T;
              validations?:
                | T
                | {
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        file?:
          | T
          | {
              name?: T;
              label?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              description?: T;
              visibleWhen?: T;
              validateWhen?: T;
              hidden?: T;
              relationTo?: T;
              mimeTypes?: T;
              maxSize?: T;
              validations?:
                | T
                | {
                    matchesField?:
                      | T
                      | {
                          field?: T;
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                    notAlreadySubmitted?:
                      | T
                      | {
                          message?: T;
                          severity?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  flow?: T;
  actions?:
    | T
    | {
        emailTeam?:
          | T
          | {
              to?: T;
              subject?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        confirmation?:
          | T
          | {
              toField?: T;
              subject?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        signedWebhook?:
          | T
          | {
              url?: T;
              secret?: T;
              id?: T;
              blockName?: T;
            };
      };
  defaultPresentation?: T;
  showResults?: T;
  resultsField?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  status?: T;
  locale?: T;
  values?: T;
  descriptors?: T;
  consent?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskForm-builder-actions".
 */
export interface TaskFormBuilderActions {
  input: {
    formId: string;
    submissionId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}