import type { IconMeta, IconNodeMap } from '../../../types'
import type { IconImportSpec } from './types'

/** Regen command named in the generated-file header when a source does not override it. */
const DEFAULT_REGEN_COMMAND = 'pnpm generate:manifests'

/** Header line telling a reader the file is generated and which command re-emits it. */
export const generatedHeader = (regenCommand: string = DEFAULT_REGEN_COMMAND): string =>
	`/* GENERATED by @10x-media/fields icon codegen. Do not edit; run \`${regenCommand}\`. */\n`

export const GENERATED_HEADER = generatedHeader()

/**
 * Node-data renders straight into the DOM via createElement(tag, attrs), so the
 * tag is restricted to the SVG shape elements lucide and tabler actually emit. An
 * unexpected tag means the upstream node shape changed; fail generation loudly
 * rather than commit data the drawer would render as an unknown element.
 */
const SVG_NODE_TAGS = new Set([
	'circle',
	'ellipse',
	'g',
	'line',
	'path',
	'polygon',
	'polyline',
	'rect',
])

/** Interpolated bare into `m.<exportName>`, so nothing but an identifier is safe. */
const EXPORT_NAME = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * The complete set of characters that can escape a single-quoted JS string:
 * the quote, the escape character, and the four line terminators. Specifiers
 * and icon names are validated rather than escaped so a bad one fails generation
 * loudly instead of emitting a module that only breaks at import time.
 */
const UNSAFE_IN_SPECIFIER = /['\\\n\r\u2028\u2029]/

export const emitManifestModule = (
	icons: IconMeta[],
	categories: string[],
	header: string = GENERATED_HEADER
): string => {
	const data = JSON.stringify({ icons, categories }, null, '\t')
	// The annotation mirrors IconMeta by hand because the generated file must stand alone
	// with no import. Anything the data can carry must be annotated, or a consumer whose
	// manifest uses an optional field fails strict typecheck against our own output.
	return `${header}export const manifest: {\n\ticons: {\n\t\tname: string\n\t\ttags: string[]\n\t\tcategories: string[]\n\t\tlabel?: string | Record<string, string>\n\t}[]\n\tcategories: string[]\n} = ${data}\n`
}

export const emitImportsModule = (
	icons: IconMeta[],
	importFor: (icon: IconMeta) => IconImportSpec,
	header: string = GENERATED_HEADER
): string => {
	const lines: string[] = [
		header,
		`import type { ComponentType } from 'react'`,
		'',
		`export type GeneratedIconModule = { default: ComponentType<{ className?: string; size?: number | string }> }`,
		'',
		'const map = {',
	]
	for (const icon of icons) {
		// The name is interpolated bare as the map key, so it needs the same guard the
		// specifier gets. `generate` rejects these too; this is the emitter standing on
		// its own, since it is exported and callable directly.
		if (UNSAFE_IN_SPECIFIER.test(icon.name)) {
			throw new Error(`unsafe icon name for an emitted key: ${icon.name}`)
		}
		const spec = importFor(icon)
		if (UNSAFE_IN_SPECIFIER.test(spec.module)) {
			throw new Error(`icon "${icon.name}": unsafe module specifier: ${spec.module}`)
		}
		if (spec.exportName !== undefined && !EXPORT_NAME.test(spec.exportName)) {
			throw new Error(`icon "${icon.name}": export name is not an identifier: ${spec.exportName}`)
		}
		if (spec.exportName) {
			lines.push(
				`\t'${icon.name}': () => import('${spec.module}').then((m) => ({ default: m.${spec.exportName} })),`
			)
		} else {
			lines.push(`\t'${icon.name}': () => import('${spec.module}'),`)
		}
	}
	lines.push('}')
	lines.push('')
	lines.push(
		'export const iconImports = map as unknown as Record<string, () => Promise<GeneratedIconModule>>'
	)
	lines.push('')
	return lines.join('\n')
}

/**
 * Emits a library's bulk glyph node-data, keyed by icon name in the same sorted
 * order as the manifest so a regeneration is byte-stable. The drawer lazily
 * imports this once per library and renders each glyph as inline SVG, which
 * replaces the per-icon dynamic imports that made large libraries scroll poorly.
 * Compact JSON keeps the committed file (thousands of glyphs) as small as the
 * source; the module is admin-only and never enters a frontend bundle.
 */
export const emitNodesModule = (
	icons: IconMeta[],
	nodes: IconNodeMap,
	header: string = GENERATED_HEADER
): string => {
	const ordered: IconNodeMap = {}
	for (const icon of icons) {
		const glyph = nodes[icon.name]
		if (!glyph) throw new Error(`icon "${icon.name}": no node-data for this manifest entry`)
		for (const [tag] of glyph) {
			if (!SVG_NODE_TAGS.has(tag)) {
				throw new Error(`icon "${icon.name}": unexpected SVG node tag "${tag}"`)
			}
		}
		ordered[icon.name] = glyph
	}
	const data = JSON.stringify(ordered)
	// Recursive alias mirroring IconNode, since a glyph may nest children under <g> or
	// <defs> and a flat tuple annotation would reject the module's own data.
	return `${header}type GeneratedIconNode =\n\t| [string, Record<string, string>]\n\t| [string, Record<string, string>, GeneratedIconNode[]]\n\nexport const nodes: Record<string, GeneratedIconNode[]> = ${data}\n`
}
