import type { IconMeta } from '../../../types'
import type { IconImportSpec } from './types'

export const GENERATED_HEADER = `/* GENERATED by @10x-media/fields icon codegen. Do not edit; run \`pnpm --filter @10x-media/fields generate:manifests\`. */\n`

export const emitManifestModule = (icons: IconMeta[], categories: string[]): string => {
	const data = JSON.stringify({ icons, categories }, null, '\t')
	return `${GENERATED_HEADER}export const manifest: {\n\ticons: { name: string; tags: string[]; categories: string[] }[]\n\tcategories: string[]\n} = ${data}\n`
}

export const emitImportsModule = (
	icons: IconMeta[],
	importFor: (icon: IconMeta) => IconImportSpec
): string => {
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { ComponentType } from 'react'`,
		'',
		`export type GeneratedIconModule = { default: ComponentType<{ className?: string; size?: number | string }> }`,
		'',
		'const map = {',
	]
	for (const icon of icons) {
		const spec = importFor(icon)
		if (spec.exportName) {
			lines.push(
				`\t'${icon.name}': () => import('${spec.module}').then((m) => ({ default: m.${spec.exportName} })),`
			)
		} else {
			lines.push(`\t'${icon.name}': () => import('${spec.module}'),`)
		}
	}
	lines.push('}')
	lines.push('')
	lines.push(
		'export const iconImports = map as unknown as Record<string, () => Promise<GeneratedIconModule>>'
	)
	lines.push('')
	return lines.join('\n')
}
