import type { IconMeta } from '../../../types'
import type { IconImportSpec } from './types'

export const GENERATED_HEADER = `/* GENERATED by @10x-media/fields icon codegen. Do not edit; run \`pnpm generate:manifests\`. */\n`

/** Interpolated bare into `m.<exportName>`, so nothing but an identifier is safe. */
const EXPORT_NAME = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * The complete set of characters that can escape a single-quoted JS string:
 * the quote, the escape character, and the four line terminators. Specifiers
 * are validated rather than escaped so a bad one fails generation loudly
 * instead of emitting a module that only breaks at import time.
 */
const UNSAFE_IN_SPECIFIER = /['\\\n\r\u2028\u2029]/

export const emitManifestModule = (icons: IconMeta[], categories: string[]): string => {
	const data = JSON.stringify({ icons, categories }, null, '\t')
	return `${GENERATED_HEADER}export const manifest: {\n\ticons: { name: string; tags: string[]; categories: string[] }[]\n\tcategories: string[]\n} = ${data}\n`
}

export const emitImportsModule = (
	icons: IconMeta[],
	importFor: (icon: IconMeta) => IconImportSpec
): string => {
	const lines: string[] = [
		GENERATED_HEADER,
		`import type { ComponentType } from 'react'`,
		'',
		`export type GeneratedIconModule = { default: ComponentType<{ className?: string; size?: number | string }> }`,
		'',
		'const map = {',
	]
	for (const icon of icons) {
		const spec = importFor(icon)
		if (UNSAFE_IN_SPECIFIER.test(spec.module)) {
			throw new Error(`icon "${icon.name}": unsafe module specifier: ${spec.module}`)
		}
		if (spec.exportName !== undefined && !EXPORT_NAME.test(spec.exportName)) {
			throw new Error(`icon "${icon.name}": export name is not an identifier: ${spec.exportName}`)
		}
		if (spec.exportName) {
			lines.push(
				`\t'${icon.name}': () => import('${spec.module}').then((m) => ({ default: m.${spec.exportName} })),`
			)
		} else {
			lines.push(`\t'${icon.name}': () => import('${spec.module}'),`)
		}
	}
	lines.push('}')
	lines.push('')
	lines.push(
		'export const iconImports = map as unknown as Record<string, () => Promise<GeneratedIconModule>>'
	)
	lines.push('')
	return lines.join('\n')
}
