export type {
	AdminWikiPluginOptions,
	WikiAccessOptions,
	WikiChipsOptions,
	WikiCollectionOverride,
	WikiCustomTargetLabel,
	WikiCustomTargetOption,
	WikiEditorBlockOption,
	WikiEditorOptions,
	WikiHiddenOptions,
	WikiOverridesOptions,
	WikiPagesOverride,
	WikiSlugsOptions,
	WikiTriggersOptions,
	WikiVideoOptions,
	WikiViewComponents,
	WikiViewOptions,
	WikiViewSlot,
	WikiViewSlotClientProps,
	WikiViewSlotServerProps,
} from '../options'
export type {
	ResolvedWikiCustomTarget,
	ResolvedWikiOptions,
	ResolvedWikiViewOptions,
} from '../plugin/resolveOptions'
