export type {
	AdminWikiPluginOptions,
	WikiAccessOptions,
	WikiChipsOptions,
	WikiCollectionOverride,
	WikiEditorBlockOption,
	WikiEditorOptions,
	WikiHiddenOptions,
	WikiOverridesOptions,
	WikiPagesOverride,
	WikiSlugsOptions,
	WikiTriggersOptions,
	WikiVideoOptions,
	WikiViewComponents,
	WikiViewOptions,
	WikiViewSlot,
	WikiViewSlotClientProps,
	WikiViewSlotServerProps,
} from '../options'
export type { ResolvedWikiOptions, ResolvedWikiViewOptions } from '../plugin/resolveOptions'
