/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    'analytics-events': AnalyticsEvent;
    'analytics-rollups': AnalyticsRollup;
    'analytics-seen': AnalyticsSeen;
    'analytics-daily': AnalyticsDaily;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    'analytics-rollups': AnalyticsRollupsSelect<false> | AnalyticsRollupsSelect<true>;
    'analytics-seen': AnalyticsSeenSelect<false> | AnalyticsSeenSelect<true>;
    'analytics-daily': AnalyticsDailySelect<false> | AnalyticsDailySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    'analytics-metric': AnalyticsMetricWidget;
    'analytics-trend': AnalyticsTrendWidget;
    'analytics-realtime': AnalyticsRealtimeWidget;
    'analytics-breakdown-pages': AnalyticsBreakdownPagesWidget;
    'analytics-breakdown-sources': AnalyticsBreakdownSourcesWidget;
    'analytics-breakdown-devices': AnalyticsBreakdownDevicesWidget;
    'analytics-breakdown-countries': AnalyticsBreakdownCountriesWidget;
    'dev-custom-sources': DevCustomSourcesWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'analytics-warm-cache': TaskAnalyticsWarmCache;
      'analytics-sync': TaskAnalyticsSync;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: string;
  timestamp: string;
  type: 'pageview' | 'event';
  name?: string | null;
  path: string;
  hostname: string;
  referrer?: string | null;
  device?: string | null;
  source?: string | null;
  country?: string | null;
  region?: string | null;
  city?: string | null;
  visitorHash: string;
  sessionId: string;
  durationMs?: number | null;
  props?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-rollups".
 */
export interface AnalyticsRollup {
  id: string;
  granularity: string;
  period: string;
  path: string;
  dimension: string;
  dimvalue: string;
  pageviews: number;
  events: number;
  durationMs: number;
  visitors: number;
  sessions: number;
  samples: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-seen".
 */
export interface AnalyticsSeen {
  id: string;
  bucket: string;
  kind: string;
  value: string;
  period: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily".
 */
export interface AnalyticsDaily {
  id: string;
  source: string;
  date: string;
  pageviews?: number | null;
  visitors?: number | null;
  sessions?: number | null;
  avgDuration?: number | null;
  bounceRate?: number | null;
  events?: number | null;
  syncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'analytics-warm-cache' | 'analytics-sync';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'analytics-warm-cache' | 'analytics-sync') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: string | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'analytics-rollups';
        value: string | AnalyticsRollup;
      } | null)
    | ({
        relationTo: 'analytics-seen';
        value: string | AnalyticsSeen;
      } | null)
    | ({
        relationTo: 'analytics-daily';
        value: string | AnalyticsDaily;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  timestamp?: T;
  type?: T;
  name?: T;
  path?: T;
  hostname?: T;
  referrer?: T;
  device?: T;
  source?: T;
  country?: T;
  region?: T;
  city?: T;
  visitorHash?: T;
  sessionId?: T;
  durationMs?: T;
  props?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-rollups_select".
 */
export interface AnalyticsRollupsSelect<T extends boolean = true> {
  granularity?: T;
  period?: T;
  path?: T;
  dimension?: T;
  dimvalue?: T;
  pageviews?: T;
  events?: T;
  durationMs?: T;
  visitors?: T;
  sessions?: T;
  samples?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-seen_select".
 */
export interface AnalyticsSeenSelect<T extends boolean = true> {
  bucket?: T;
  kind?: T;
  value?: T;
  period?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily_select".
 */
export interface AnalyticsDailySelect<T extends boolean = true> {
  source?: T;
  date?: T;
  pageviews?: T;
  visitors?: T;
  sessions?: T;
  avgDuration?: T;
  bounceRate?: T;
  events?: T;
  syncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-metric_widget".
 */
export interface AnalyticsMetricWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'x-small' | 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-trend_widget".
 */
export interface AnalyticsTrendWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-realtime_widget".
 */
export interface AnalyticsRealtimeWidget {
  data?: {
    title?: string | null;
    metric: 'visitors' | 'pageviews';
    windowMinutes?: ('5' | '15' | '30' | '60') | null;
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-breakdown-pages_widget".
 */
export interface AnalyticsBreakdownPagesWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    limit?: number | null;
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-breakdown-sources_widget".
 */
export interface AnalyticsBreakdownSourcesWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    limit?: number | null;
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-breakdown-devices_widget".
 */
export interface AnalyticsBreakdownDevicesWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    limit?: number | null;
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-breakdown-countries_widget".
 */
export interface AnalyticsBreakdownCountriesWidget {
  data?: {
    title?: string | null;
    metric: 'pageviews' | 'visitors' | 'sessions' | 'avgDuration' | 'bounceRate' | 'events';
    timeframe:
      | 'today'
      | 'last7days'
      | 'last30days'
      | 'last90days'
      | 'thisMonth'
      | 'thisYear'
      | 'lastYear'
      | 'allTime'
      | 'custom';
    range?: {
      from?: string | null;
      to?: string | null;
    };
    limit?: number | null;
    dataSource?: ('native' | 'posthog') | null;
  };
  width: 'small' | 'medium' | 'large';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dev-custom-sources_widget".
 */
export interface DevCustomSourcesWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAnalytics-warm-cache".
 */
export interface TaskAnalyticsWarmCache {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAnalytics-sync".
 */
export interface TaskAnalyticsSync {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}